"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDown, ArrowUpRight, Check, Heart, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, UserRound, X } from "lucide-react";
import * as THREE from "three";

type Product={id:number;name:string;price:number;tag:string;desc:string;category:string;material:string};
const products:Product[]=[
 {id:1,name:"Aleri No. 01 — Obsidian Tee",price:3490,tag:"SIGNATURE",desc:"Heavyweight 280 GSM cotton with an architectural silhouette.",category:"T-Shirts",material:"280 GSM premium cotton"},
 {id:2,name:"Aleri No. 02 — Ivory Form",price:3990,tag:"NEW",desc:"Soft ivory jersey with a deliberately relaxed cut.",category:"T-Shirts",material:"Premium combed cotton"},
 {id:3,name:"Aleri No. 03 — Noir Atelier",price:4290,tag:"ATELIER",desc:"Minimal black form with an elevated hand-feel.",category:"Atelier",material:"Luxury cotton jersey"},
 {id:4,name:"Aleri No. 04 — Mineral Overshirt",price:5490,tag:"LIMITED",desc:"Structured overshirt designed as an outer layer.",category:"Outerwear",material:"Heavyweight twill"}
];

function ProductScene({productId=1}:{productId?:number}){
 const ref=useRef<HTMLDivElement>(null); const [rot,setRot]=useState({x:-.12,y:.3}); const [zoom,setZoom]=useState(1);
 useEffect(()=>{if(!ref.current)return; const host=ref.current; host.innerHTML="";
  const scene=new THREE.Scene(); const camera=new THREE.PerspectiveCamera(35,1,.1,100); camera.position.set(0,0,5);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(window.devicePixelRatio,2)); renderer.setSize(host.clientWidth,host.clientHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; host.appendChild(renderer.domElement);
  const group=new THREE.Group(); scene.add(group);
  const mat=new THREE.MeshPhysicalMaterial({color:productId===2?0xe9e4da:productId===4?0x77746e:0x111111,roughness:.32,metalness:.04});
  const body=new THREE.Mesh(new THREE.BoxGeometry(1.55,2.25,.48,8,12,4),mat); group.add(body);
  const sleeveGeo=new THREE.CylinderGeometry(.34,.5,1.55,20); const l=new THREE.Mesh(sleeveGeo,mat), r=new THREE.Mesh(sleeveGeo,mat); l.position.set(-1.02,.48,0); r.position.set(1.02,.48,0); l.rotation.z=-.35;r.rotation.z=.35;group.add(l,r);
  const neck=new THREE.Mesh(new THREE.TorusGeometry(.25,.11,12,32),new THREE.MeshPhysicalMaterial({color:0x090909,roughness:.5})); neck.position.y=1.02; neck.rotation.x=Math.PI/2; group.add(neck);
  const seam=new THREE.Mesh(new THREE.BoxGeometry(.025,1.7,.02),new THREE.MeshBasicMaterial({color:0x777777})); seam.position.z=.25; group.add(seam);
  scene.add(new THREE.DirectionalLight(0xffffff,3)); const fill=new THREE.DirectionalLight(0xd9d2c4,2);fill.position.set(-4,1,3);scene.add(fill);scene.add(new THREE.AmbientLight(0xffffff,1.2));
  const onMove=(e:PointerEvent)=>{if(e.buttons===1)setRot(v=>({x:Math.max(-.55,Math.min(.55,v.x+e.movementY*.008)),y:v.y+e.movementX*.008}))}; host.addEventListener("pointermove",onMove);
  let raf=0; const animate=()=>{group.rotation.x=rot.x;group.rotation.y=rot.y;group.scale.setScalar(zoom);renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();
  const resize=()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix();renderer.setSize(w,h)};resize();window.addEventListener("resize",resize);
  return()=>{cancelAnimationFrame(raf);host.removeEventListener("pointermove",onMove);window.removeEventListener("resize",resize);renderer.dispose();host.innerHTML=""};
 },[productId,rot,zoom]);
 return <div className="scene-wrap"><div ref={ref} className="three-scene"/><div className="scene-tools"><button onClick={()=>setZoom(z=>Math.min(1.35,z+.1))}><Plus/></button><button onClick={()=>setZoom(z=>Math.max(.8,z-.1))}><Minus/></button><span>DRAG TO ROTATE · 3D</span></div></div>
}

export default function Home(){
 const [filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[search,setSearch]=useState(false),[cartOpen,setCartOpen]=useState(false),[account,setAccount]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState("M"),[cart,setCart]=useState<Record<string,{qty:number,size:string}>>({}),[wish,setWish]=useState<number[]>([]);
 useEffect(()=>{try{const c=localStorage.getItem("aleri-cart");if(c)setCart(JSON.parse(c));const w=localStorage.getItem("aleri-wish");if(w)setWish(JSON.parse(w))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("aleri-cart",JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem("aleri-wish",JSON.stringify(wish))},[wish]);
 const visible=useMemo(()=>products.filter(p=>(filter==="All"||p.category===filter)&&(p.name+" "+p.category).toLowerCase().includes(query.toLowerCase())),[filter,query]);
 const count=Object.values(cart).reduce((a,b)=>a+b.qty,0); const total=Object.entries(cart).reduce((s,[id,v])=>s+(products.find(p=>p.id===+id)?.price||0)*v.qty,0);
 const add=(p:Product)=>setCart(c=>({...c,[p.id]:{qty:(c[p.id]?.qty||0)+1,size}}));
 const change=(id:number,n:number)=>setCart(c=>{const v=c[id];if(!v)return c;const q=v.qty+n;if(q<=0){const x={...c};delete x[id];return x}return {...c,[id]:{...v,qty:q}}});
 const checkout=()=>alert("Checkout is ready for live payment credentials. Connect Razorpay or Stripe to charge customers.");
 return <main>
 <header className="nav"><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="logo" href="#top">MAISON <i>ALERI</i></a><nav><a href="#collection">Collection</a><a href="#house">The House</a><a href="#journal">Journal</a></nav><div className="nav-actions"><button onClick={()=>setSearch(true)}><Search/></button><button onClick={()=>setAccount(true)}><UserRound/></button><button className="bag" onClick={()=>setCartOpen(true)}><ShoppingBag/><b>{count}</b></button></div></header>
 {menu&&<div className="mobile-menu"><a href="#collection" onClick={()=>setMenu(false)}>Collection</a><a href="#house" onClick={()=>setMenu(false)}>The House</a><a href="#journal" onClick={()=>setMenu(false)}>Journal</a></div>}
 <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">MAISON ALERI / EST. 2026</p><h1>Quietly<br/><em>extraordinary.</em></h1><p className="lead">A digital fashion house built around considered forms, uncompromising materials and immersive commerce.</p><div className="hero-actions"><a className="primary" href="#collection">Discover the collection <ArrowUpRight/></a><a className="text-link" href="#house">Enter the house <ArrowDown/></a></div></div><ProductScene/><div className="hero-bottom"><span>REAL-TIME WEBGL</span><span>DRAG / ZOOM / EXPLORE</span><span>INDIA / WORLDWIDE</span></div></section>
 <section className="manifesto" id="house"><p className="eyebrow">THE MAISON</p><h2>Luxury is not excess.<br/><em>It is intention.</em></h2><p>Every proportion, texture and detail exists for a reason. Maison Aleri is designed to feel tactile before it arrives at your door.</p></section>
 <section className="collection" id="collection"><div className="section-head"><div><p className="eyebrow">01 — THE COLLECTION</p><h2>Objects of <em>desire.</em></h2></div><span className="count-label">{visible.length} PIECES</span></div><div className="filter-row">{["All","T-Shirts","Outerwear","Atelier"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="product-grid">{visible.map(p=><motion.article key={p.id} className="product" initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className={"product-visual p"+(p.id-1)} onClick={()=>setSelected(p)}><span>{p.tag}</span><button onClick={e=>{e.stopPropagation();setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}}><Heart fill={wish.includes(p.id)?"currentColor":"none"}/></button><ProductScene productId={p.id}/></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.desc}</p></div><strong>₹{p.price.toLocaleString("en-IN")}</strong></div><button className="add" onClick={()=>setSelected(p)}>View piece <ArrowUpRight/></button></motion.article>)}</div></section>
 <section className="editorial" id="journal"><div className="editorial-image"><div className="editorial-mark">A</div></div><div className="editorial-copy"><p className="eyebrow">02 — THE JOURNAL</p><h2>The art of<br/><em>less.</em></h2><p>Inside the visual language of Maison Aleri: monochrome architecture, tactile cotton and the pursuit of a silhouette that feels inevitable.</p><button className="primary dark" onClick={()=>alert("Journal chapter: The Art of Less.")}>Read the story <ArrowUpRight/></button></div></section>
 <section className="future"><Sparkles/><p className="eyebrow">THE NEXT CHAPTER</p><h2>Designed in the digital.<br/><em>Made for the real world.</em></h2><p>Immersive commerce, considered objects and a house that evolves with you.</p></section>
 <footer><div><a className="logo" href="#top">MAISON <i>ALERI</i></a><p>A house of modern luxury.</p></div><div className="footer-links"><a href="#collection">Collection</a><a href="#journal">Journal</a><button onClick={()=>alert("Contact: hello@maisonaleri.com")}>Contact</button><button onClick={()=>alert("Instagram will be connected here.")}>Instagram</button></div><small>© 2026 Maison Aleri. All rights reserved.</small></footer>
 <button className="cart-pill" onClick={()=>setCartOpen(true)}><ShoppingBag/> {count} {count===1?"piece":"pieces"} <span>•</span> ₹{total.toLocaleString("en-IN")}</button>
 <AnimatePresence>{search&&<div className="overlay" onClick={()=>setSearch(false)}><motion.div className="search-panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSearch(false)}><X/></button><p className="eyebrow">SEARCH MAISON ALERI</p><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pieces..." />{query&&visible.map(p=><button className="result" key={p.id} onClick={()=>{setSelected(p);setSearch(false)}}><span>{p.name}</span><span>₹{p.price.toLocaleString("en-IN")}</span></button>)}</motion.div></div>}</AnimatePresence>
 <AnimatePresence>{cartOpen&&<div className="overlay drawer-backdrop" onClick={()=>setCartOpen(false)}><motion.aside className="cart-drawer" onClick={e=>e.stopPropagation()} initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}}><div className="drawer-head"><h3>Your bag</h3><button onClick={()=>setCartOpen(false)}><X/></button></div>{!count?<div className="empty"><ShoppingBag/><p>Your bag is waiting.</p><a href="#collection" onClick={()=>setCartOpen(false)}>Explore collection</a></div>:<><div className="cart-items">{Object.entries(cart).map(([id,v])=>{const p=products.find(x=>x.id===+id)!;return <div className="cart-item" key={id}><div className="cart-thumb"><ProductScene productId={p.id}/></div><div><h4>{p.name}</h4><small>Size {v.size}</small><strong>₹{(p.price*v.qty).toLocaleString("en-IN")}</strong><div className="qty"><button onClick={()=>change(+id,-1)}><Minus/></button><b>{v.qty}</b><button onClick={()=>change(+id,1)}><Plus/></button></div></div><button onClick={()=>change(+id,-v.qty)}><X/></button></div>})}</div><div className="checkout"><div><span>Subtotal</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><small>Taxes and shipping calculated at checkout.</small><button className="primary full" onClick={checkout}>Secure checkout <ArrowUpRight/></button></div></>}</motion.aside></div>}</AnimatePresence>
 <AnimatePresence>{account&&<div className="overlay" onClick={()=>setAccount(false)}><motion.div className="account-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAccount(false)}><X/></button><p className="eyebrow">THE PRIVATE CLIENT</p><h2>Your Maison.<br/><em>Your world.</em></h2><p>Account architecture is ready for secure authentication.</p><button className="primary full" onClick={()=>alert("Connect your authentication provider to enable live accounts.")}>Continue with email <ArrowUpRight/></button><button className="ghost full" onClick={()=>setAccount(false)}>Continue as guest</button></motion.div></div>}</AnimatePresence>
 <AnimatePresence>{selected&&<div className="overlay" onClick={()=>setSelected(null)}><motion.div className="product-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><ProductScene productId={selected.id}/><div className="modal-info"><p className="eyebrow">{selected.tag} / {selected.category}</p><h2>{selected.name}</h2><strong>₹{selected.price.toLocaleString("en-IN")}</strong><p>{selected.desc}</p><p className="material">{selected.material}</p><small className="label-small">SELECT SIZE</small><div className="sizes">{["XS","S","M","L","XL"].map(s=><button className={size===s?"active":""} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><button className="primary full" onClick={()=>{add(selected);setSelected(null);setCartOpen(true)}}>Add to bag <ArrowUpRight/></button><div className="detail-line"><Check/> Made to order · POD-ready fulfillment</div></div></motion.div></div>}</AnimatePresence>
 </main>
}