"use client";

import {motion,AnimatePresence} from "framer-motion";
import {ArrowDown,ArrowUpRight,Heart,Menu,Search,ShoppingBag,Sparkles,UserRound,X,Minus,Plus,Trash2,Check} from "lucide-react";
import {useMemo,useState} from "react";

type Product={id:number;name:string;price:number;tag:string;desc:string;category:string};
const products:Product[]=[
{id:1,name:"Aleri No. 01 — Obsidian Tee",price:3490,tag:"SIGNATURE",desc:"Heavyweight 280 GSM cotton, architectural silhouette.",category:"T-Shirts"},
{id:2,name:"Aleri No. 02 — Ivory Form",price:3990,tag:"NEW",desc:"Soft ivory jersey with a deliberately relaxed cut.",category:"T-Shirts"},
{id:3,name:"Aleri No. 03 — Noir Atelier",price:4290,tag:"ATELIER",desc:"Minimal black form with an elevated hand-feel.",category:"Atelier"},
{id:4,name:"Aleri No. 04 — Mineral Overshirt",price:5490,tag:"LIMITED",desc:"Structured overshirt designed as an outer layer.",category:"Outerwear"}
];

function Garment3D(){return <div className="stage"><div className="halo"/><motion.div className="garment" animate={{rotateY:[-10,10,-10],rotateX:[2,-2,2]}} transition={{duration:8,repeat:Infinity,ease:"easeInOut"}}><div className="shoulder left"/><div className="shoulder right"/><div className="body"/><div className="neck"/><div className="sleeve left"/><div className="sleeve right"/><div className="label">ALERI</div></motion.div><div className="stage-caption"><span>01 / 03</span><span>SCULPTED FORM</span></div></div>}

export default function Home(){
 const [menu,setMenu]=useState(false),[cart,setCart]=useState<Record<number,number>>({}),[wishlist,setWishlist]=useState<number[]>([]),[query,setQuery]=useState(""),[searchOpen,setSearchOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState("M");
 const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
 const remove=(id:number)=>setCart(c=>{const n={...c};delete n[id];return n});
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 const total=Object.entries(cart).reduce((sum,[id,qty])=>sum+(products.find(p=>p.id===+id)?.price||0)*qty,0);
 const results=useMemo(()=>products.filter(p=>(p.name+" "+p.category).toLowerCase().includes(query.toLowerCase())),[query]);

 return <main>
  <header className="nav"><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="logo" href="#">MAISON <i>ALERI</i></a><nav><a href="#collection">Collection</a><a href="#house">The House</a><a href="#journal">Journal</a></nav><div className="nav-actions"><button onClick={()=>setSearchOpen(true)} aria-label="Search"><Search/></button><button onClick={()=>setAccountOpen(true)} aria-label="Account"><UserRound/></button><button className="bag" onClick={()=>setCartOpen(true)} aria-label="Bag"><ShoppingBag/><b>{count}</b></button></div></header>
  {menu&&<div className="mobile-menu"><a href="#collection" onClick={()=>setMenu(false)}>Collection</a><a href="#house" onClick={()=>setMenu(false)}>The House</a><a href="#journal" onClick={()=>setMenu(false)}>Journal</a></div>}
  <AnimatePresence>{searchOpen&&<motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="search-panel" initial={{y:-40}} animate={{y:0}}><button className="close" onClick={()=>setSearchOpen(false)}><X/></button><p className="eyebrow">SEARCH MAISON ALERI</p><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pieces, collections..." />{query&&<div className="search-results">{results.map(p=><button key={p.id} onClick={()=>{setSelected(p);setSearchOpen(false)}}><span>{p.name}</span><span>₹{p.price.toLocaleString("en-IN")}</span></button>)}{!results.length&&<p>No pieces found.</p>}</div>}</motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{cartOpen&&<motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setCartOpen(false)}><motion.aside className="cart-drawer" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} onClick={e=>e.stopPropagation()}><div className="drawer-head"><h3>Your bag</h3><button onClick={()=>setCartOpen(false)}><X/></button></div>{count===0?<div className="empty"><ShoppingBag/><p>Your bag is waiting.</p><a href="#collection" onClick={()=>setCartOpen(false)}>Explore the collection</a></div>:<><div className="cart-items">{Object.entries(cart).map(([id,qty])=>{const p=products.find(x=>x.id===+id)!;return <div className="cart-item" key={id}><div className={"cart-thumb p"+(p.id-1)}><div className="mini-garment"/></div><div><h4>{p.name}</h4><small>Size {size} · Qty {qty}</small><strong>₹{(p.price*qty).toLocaleString("en-IN")}</strong></div><button onClick={()=>remove(p.id)}><Trash2/></button></div>})}</div><div className="checkout"><div><span>Subtotal</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><small>Shipping calculated at checkout.</small><button className="primary full">Secure checkout <ArrowUpRight/></button></div></>}</motion.aside></motion.div></AnimatePresence>
  <AnimatePresence>{accountOpen&&<div className="overlay" onClick={()=>setAccountOpen(false)}><motion.div className="account-modal" initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAccountOpen(false)}><X/></button><p className="eyebrow">THE PRIVATE CLIENT</p><h2>Your Maison.<br/><em>Your world.</em></h2><p>Create an account to save your wardrobe, track orders and receive private access to new releases.</p><button className="primary full">Continue with email <ArrowUpRight/></button><button className="ghost full">Continue as guest</button></motion.div></div>}</AnimatePresence>
  <AnimatePresence>{selected&&<div className="overlay" onClick={()=>setSelected(null)}><motion.div className="product-modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className={"modal-visual p"+(selected.id-1)}><div className="mini-garment large"/></div><div className="modal-info"><p className="eyebrow">{selected.tag} / {selected.category}</p><h2>{selected.name}</h2><strong>₹{selected.price.toLocaleString("en-IN")}</strong><p>{selected.desc}</p><div><small className="label-small">SELECT SIZE</small><div className="sizes">{["XS","S","M","L","XL"].map(s=><button className={size===s?"active":""} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div></div><button className="primary full" onClick={()=>{add(selected.id);setSelected(null);setCartOpen(true)}}>Add to bag <ArrowUpRight/></button><div className="detail-line"><Check/> Free delivery on orders over ₹7,500</div><div className="detail-line"><Check/> Made to order via our fulfillment partner</div></div></motion.div></div>}</AnimatePresence>

  <section className="hero"><div className="hero-copy"><p className="eyebrow">MAISON ALERI / EST. 2026</p><h1>Quietly<br/><em>extraordinary.</em></h1><p className="lead">A new house of modern luxury. Considered forms, uncompromising materials, and pieces made to outlive the moment.</p><div className="hero-actions"><a className="primary" href="#collection">Discover the collection <ArrowUpRight/></a><a className="text-link" href="#house">Enter the house <ArrowDown/></a></div></div><Garment3D/><div className="hero-bottom"><span>MADE FOR THE FEW</span><span>INDIA / WORLDWIDE</span><span>SCROLL TO EXPLORE ↓</span></div></section>
  <section className="manifesto" id="house"><p className="eyebrow">THE MAISON</p><h2>Luxury is not excess.<br/><em>It is intention.</em></h2><p>Maison Aleri creates contemporary wardrobe pieces through restraint. Every proportion, texture and detail exists for a reason. No noise. No compromise.</p></section>
  <section className="collection" id="collection"><div className="section-head"><div><p className="eyebrow">01 — THE COLLECTION</p><h2>Objects of <em>desire.</em></h2></div><a href="#collection">View all pieces <ArrowUpRight/></a></div><div className="filter-row">{["All","T-Shirts","Outerwear","Atelier"].map(f=><button key={f}>{f}</button>)}</div><div className="product-grid">{products.map((p,i)=><motion.article key={p.id} className="product" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><div className={"product-visual p"+i} onClick={()=>setSelected(p)}><span>{p.tag}</span><button onClick={e=>{e.stopPropagation();setWishlist(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}}><Heart fill={wishlist.includes(p.id)?"currentColor":"none"}/></button><div className="mini-garment"/></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.desc}</p></div><strong>₹{p.price.toLocaleString("en-IN")}</strong></div><button className="add" onClick={()=>setSelected(p)}>View piece <ArrowUpRight/></button></motion.article>)}</div></section>
  <section className="editorial" id="journal"><div className="editorial-image"><div className="editorial-mark">A</div></div><div className="editorial-copy"><p className="eyebrow">02 — THE JOURNAL</p><h2>The art of<br/><em>less.</em></h2><p>Inside the visual language of Maison Aleri: monochrome architecture, tactile cotton and the pursuit of a silhouette that feels inevitable.</p><a className="primary dark" href="#journal">Read the story <ArrowUpRight/></a></div></section>
  <section className="future"><Sparkles/><p className="eyebrow">THE NEXT CHAPTER</p><h2>Designed in the digital.<br/><em>Made for the real world.</em></h2><p>Immersive commerce, considered objects and a house that evolves with you.</p></section>
  <footer><div><a className="logo" href="#">MAISON <i>ALERI</i></a><p>A house of modern luxury.</p></div><div className="footer-links"><a href="#">Shipping</a><a href="#">Returns</a><a href="#">Contact</a><a href="#">Instagram</a></div><small>© 2026 Maison Aleri. All rights reserved.</small></footer>
  <div className="cart-pill" onClick={()=>setCartOpen(true)}><ShoppingBag/> {count} {count===1?"piece":"pieces"} <span>•</span> ₹{total.toLocaleString("en-IN")}</div>
 </main>
}